export enum ProductStatus {
  Active,
  Inactive
}

export enum ProductGender {
  Male,
  Female,
  Children,
  Baby
}

export enum ProductSize {
  XS,
  S,
  M,
  L,
  XL,
  XXL
}
export const categoryTitle = {
  shirt: 'ÁO',
  poloShirt: 'Áo Polo',
  't-Shirt': 'Áo Thun',
  'sweatShirts&Hoodies': 'Áo Nỉ & Hoodie',
  'sweater&cardigan': 'Áo Len và Cardigan',
  officeShirt: 'Áo Sơ Mi Công Sở',
  casualShirt: 'Áo Sơ Mi Casual',
  peaceForAll: 'PEACE FOR ALL',
  'printed t-Shirt': 'Áo Thun In Hoạ Tiết',
  SPORTWEAR: 'SPORT UTILYTY WEAR',
  sportWear: 'sport utility wear',
  outerWear: 'ĐỒ MẶC NGOÀI',
  allOuterWear: 'Tất Cả Đồ Mặc Ngoài',
  'blousonShirt&parkaShirt': 'Áo Blouson & Áo Parka',
  miracleAirJacket: 'Áo Khoác Miracle Air',
  'jacket&blazer': 'Áo Khoác & Áo Blazer',
  longGown: 'Áo Choàng Dáng Dài',
  'superLightJacket&pufftech': 'Áo Khoác Siêu Nhẹ & PUFFTECH',
  preventShineProduct: 'SẢN PHẨM CHỐNG NẮNG',
  allOfProduct: 'Tất Cả Sản Phẩm',
  pants: 'QUẦN',
  allOfPants: 'Tất Cả Quần',
  shortPants: 'Quần Short',
  miracleAirPants: 'Quần Miracle Air',
  ankleLengthPants: 'Quần Dài Đến Mắt Cá',
  'jean&coloredJean': 'Quần Jean & Quần Jean Màu',
  looseLongPants: 'Quần Dài Dáng Rộng',
  chinoPants: 'Quần Chino',
  trouserPants: 'Quần Tây',
  casualPants: 'Quần Casual',
  fleecePants: 'Quần Nỉ',
  underWear: 'ĐỒ MẶC TRONG & ĐỒ LÓT',
  allOfUnderWear: 'Tất Cả Đồ Mặc Trong & Đồ Lót',
  alrismUnderWear: 'AlRism Đồ Mặc Trong',
  'boxerUnderWear&Brief': 'Quần Lót Boxer & Brief',
  sock: 'Tất',
  'heattechUnderWear&ThermalUnderWear': 'HEATTECH Đồ Mặc Trong & Quần Lót Giữ Nhiệt',
  'leggings&shockPant': 'Quần Leggings và Quần Tất',
  accessories: 'PHỤ KIỆN',
  allOfAccessories: 'Tất Cả Phụ Kiện',
  bag: 'Túi',
  sunglasses: 'Kính Mát',
  'hat&cap': 'Mũ & Mũ Lưỡi Trai',
  belt: 'Thắt Lưng',
  umbrella: 'Ô',
  scarves: 'Khăn Choàng & Khăn Choàng Cổ',
  gloves: 'Găng Tay',
  different: 'Khác',
  homeWear: 'ĐỒ MĂC NHÀ',
  allOfhomeWear: 'Tất Cả Đồ Mặc Nhà',
  'homeWear&Pyjama': 'Đồ Mặc Nhà & Pyjama',
  'easyPant&Relaxed': 'Quần Easy & Relaxed',
  slipper: 'Dép Đi Trong Nhà',
  baby0yto1y: 'TRẺ SƠ SINH (0-1 NĂM)',
  allOfbaby0yto1y: 'Tất Cả Đồ Trẻ Sơ Sinh',
  onePieceSuit: 'Đồ Liền Mảnh',
  bodySuit: 'Bodysuit',
  baby6mto5y: 'TRẺ (6 THÁNG - 5 NĂM)',
  'dresses&skirts': 'ĐẦM & CHÂN VÁY',
  dresses: 'Đầm',
  skirt: 'Chân Váy',
  'dress&Jumpsuit': 'Đầm & Jumpsuit',
  'bra&BraTops': 'Áo Bra và Bratops',
  PREGNANTCLOTHES: 'ĐỒ BẦU',
  pregnantClothes: 'Đồ Bầu'
}
export enum ProductColor {
  OFFWHITE = 0,
  'LIGHT GRAY' = 2,
  GRAY = 3,
  'DARK GRAY' = 8,
  BLACK = 9,
  PINK = 10,
  RED = 16,
  ORANGE = 27,
  NATURAL = 30,
  BEIGE = 32,
  KHAKI = 33,
  'DARK BROWN' = 38,
  YELLOW = 41,
  OLIVE = 56,
  BLUE = 63,
  NAVY = 69
}
